---
# Где храним vhost
nginx_sites_available_dir: /etc/nginx/sites-available
nginx_sites_enabled_dir: /etc/nginx/sites-enabled
nginx_conf_d_dir: /etc/nginx/conf.d

# Имя vhost-файла: по умолчанию домен ноды, иначе — digitalstreamers.xyz
nginx_vhost_name: "{{ remnawave_node_domain | default('digitalstreamers.xyz') }}"

# Порт/адрес назначения HTTPS на ноде
nginx_https_bind: "0.0.0.0:4443"

# Домены, на которые отвечает vhost
website_domains:
  - "{{ remnawave_node_domain | default('digitalstreamers.xyz') }}"
