remnawave_node_write_env: true
remnawave_node_port: 2222
remnawave_node_env_content: |
  NODE_PORT={{ remnawave_node_port }}
  SECRET_KEY={{ remnawave_secret_key }}

remnawave_node_address: "77.239.127.199"
remnawave_node_name: "{{ inventory_hostname }}"

remnawave_host_address: "edge-fra-01.digitalstreamers.xyz"
remnawave_node_country_code: "DE"
remnawave_host_remark: "üá©üá™ 1 vpn-for-friends"
remnawave_host_sni: ""
remnawave_inbound_tag: "VLESS TCP REALITY"

# –ó–æ–Ω–∞, –≤ –∫–æ—Ç–æ—Ä–æ–π —Å–æ–∑–¥–∞—ë–º –∑–∞–ø–∏—Å—å
cf_dns_zone: "digitalstreamers.xyz"

# –ù–∞–±–æ—Ä –∑–∞–ø–∏—Å–µ–π –¥–ª—è —ç—Ç–æ–π –Ω–æ–¥—ã
cf_dns_records:
  - name: "edge-fra-01"        # => edge-fra-01.digitalstreamers.xyz
    type: "A"
    value: "{{ remnawave_node_address }}"    # –ø—É–±–ª–∏—á–Ω—ã–π IP –Ω–æ–¥—ã
    proxied: false             # –í–ê–ñ–ù–û: Reality/HAProxy –Ω—É–∂–Ω—ã —Å —Ä–µ–∞–ª—å–Ω—ã–º IP ‚Üí —Å–µ—Ä—ã–π –æ–±–ª–∞—á–∫–æ!
    ttl: 300
