remnawave_node_write_env: true
remnawave_node_port: 2222
remnawave_node_env_content: |
  NODE_PORT={{ remnawave_node_port }}
  SECRET_KEY={{ remnawave_secret_key }}

timezone: Europe/Moscow

remnawave_node_address: "92.53.115.21"
remnawave_node_name: "{{ inventory_hostname }}"

remnawave_host_address: "edge-spb-02.digitalstreamers.xyz"
remnawave_node_country_code: "RU"
remnawave_host_remark: "üá∑üá∫ 2 vpn-for-friends"
remnawave_host_sni:
  - "cloudflare.com"
  - "www.cloudflare.com"

remnawave_inbound_tag: "VLESS TCP REALITY"

# –ù–∞–±–æ—Ä –∑–∞–ø–∏—Å–µ–π –¥–ª—è —ç—Ç–æ–π –Ω–æ–¥—ã
cf_dns_records:
  - { name: "www",               type: "A", proxied: false }
  - { name: "site",              type: "A", proxied: false }
  - { name: "edge-spb-02",       type: "A", proxied: false }

# –¥–æ–º–µ–Ω—ã, –ø–æ –∫–æ—Ç–æ—Ä—ã–º –Ω–æ–¥–∞ –¥–æ–ª–∂–Ω–∞ –æ—Ç–¥–∞–≤–∞—Ç—å —Å–≤–æ–π nginx (—á–µ—Ä–µ–∑ HAProxy)
haproxy_node_nginx_sni_domains:
  - site.digitalstreamers.xyz
  - www.digitalstreamers.xyz

# –∞–¥—Ä–µ—Å nginx –Ω–∞ –Ω–æ–¥–µ (—Ç–æ—Ç –∂–µ, —á—Ç–æ nginx_https_bind –≤ remnawave_node_nginx)
haproxy_node_nginx_host: "127.0.0.1"
haproxy_node_nginx_port: 4443
