---
remnawave_panel_frontend_domain: remna.vpn-for-friends.com

remnawave_panel_telegram_enabled: true
remnawave_panel_telegram_bot_token: "{{ vault_remnawave_panel_telegram_bot_token }}"
remnawave_panel_telegram_users_chat_id: "-1003288172821"     # канал/чат для событий по пользователям
remnawave_panel_telegram_nodes_chat_id: "-1003288172821"     # для нод
remnawave_panel_telegram_crm_chat_id:   "-1003288172821"     # для CRM/платежей

# Вебхук (опционально, если у тебя есть внешний приёмник событий)
remnawave_panel_webhook_enabled: false
# remnawave_panel_webhook_url: "https://your-endpoint.example.com/remnawave"
# remnawave_panel_webhook_secret_header: "{{ vault_remnawave_panel_webhook_secret_header }}"  # 64 символа

# метрики
remnawave_panel_metrics_user: admin
remnawave_panel_metrics_pass: "{{ vault_remnawave_panel_metrics_pass }}"

# postgres
remnawave_panel_pg_user: postgres
remnawave_panel_pg_db: postgres
remnawave_panel_pg_password: "{{ vault_remnawave_panel_pg_password }}"

# JWT
remnawave_panel_jwt_auth_secret: "{{ vault_remnawave_panel_jwt_auth_secret }}"
remnawave_panel_jwt_api_tokens_secret: "{{ vault_remnawave_panel_jwt_api_tokens_secret }}"

cf_dns_zone: "vpn-for-friends.com"
cf_dns_target_ip: "77.239.127.199"

# Хотим поднять remna.vpn-for-friends.com и api.vpn-for-friends.com
cf_dns_records:
  - name: "remna"
    type: "A"
    proxied: false
    ttl: 300
  - name: "api"
    type: "CNAME"
    value: "remna.vpn-for-friends.com"
    proxied: false

# Remnawave API / Inbounds (внешний интерфейс роли)
remnawave_api_base_url: "https://{{ remnawave_panel_frontend_domain }}/api"

remnawave_profile_name: "Default-Profile"
# remnawave_profile_uuid: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"

remnawave_tag_collision_mode: "auto_prefix"
remnawave_update_mode: "upsert"
remnawave_validate_config: true

remnawave_reality_private_key: "{{ vault_reality_private_key }}"
remnawave_reality_short_id: "{{ vault_reality_short_id }}"

remnawave_reality_private_key_ds: "{{ vault_reality_private_key_ds }}"
remnawave_reality_short_id_ds: "{{ vault_reality_short_id_ds }}"

remnawave_nginx_bind_address: "0.0.0.0"
remnawave_nginx_external_https_port: "4443"

# Какими инбаундами мы реально управляем через Ansible
# Если пусто/не задано — по умолчанию все, для обратной совместимости.
# "VLESS TCP REALITY" - основной инбаунд в данном случае не трогаем (он мигрировал из Marzban)
# "VLESS TCP REALITY (DS)" - второй инбаунд для тестирования маскировки под наш домен.
remnawave_inbounds_managed:
  - "VLESS TCP REALITY (DS)"

remnawave_inbounds:
  - tag: "{{ remnawave_inbound_tag }}"
    listen: "127.0.0.1"
    port: 8444
    protocol: "vless"
    sniffing:
      enabled: true
      destOverride: ["http", "tls", "quic", "fakedns"]
      metadataOnly: false
    settings:
      clients: []
      decryption: "none"
    streamSettings:
      network: "tcp"
      security: "reality"
      realitySettings:
        show: false
        dest: "www.cloudflare.com:443"
        xver: 0
        serverNames: ["www.cloudflare.com", "cloudflare.com"]
        privateKey: "{{ remnawave_reality_private_key }}"
        shortIds: ["{{ remnawave_reality_short_id }}"]
        maxTimeDiff: 0
        fingerprint: "chrome"
  - tag: "VLESS TCP REALITY (DS)"
    listen: "127.0.0.1"
    port: 8445
    protocol: "vless"
    sniffing:
      enabled: true
      destOverride: ["http", "tls", "quic", "fakedns"]
      metadataOnly: false
    settings:
      clients: []
      decryption: "none"
    streamSettings:
      network: "tcp"
      security: "reality"
      realitySettings:
        show: false
        dest: "www.digitalstreamers.xyz:443"
        xver: 0
        serverNames: [digitalstreamers.xyz]
        privateKey: "{{ remnawave_reality_private_key_ds }}"
        shortIds: ["{{ remnawave_reality_short_id_ds }}"]
        maxTimeDiff: 0
        fingerprint: "chrome"

marzban_api_base_url: "https://marzban-s2.vpn-for-friends.com:4443"
marzban_admin_username: "admin"
marzban_admin_password: "{{ vault_marzban_admin_password }}"

marzban_inbound_tag: "VLESS TCP REALITY"

# включаем legacy-режим в subscription-page
remnawave_sub_marzban_legacy_enabled: true

# из базы Marzban: SELECT secret_key FROM jwt LIMIT 1;
remnawave_sub_marzban_secret_key: "{{ vault_marzban_secret_key }}"

remnawave_sub_marzban_custom_sub_prefix: "sub"

# включаем nginx vhost для marzban-ссылок
remnawave_sub_marzban_legacy_domain: "marzban-s2.vpn-for-friends.com"
