galaxy_info:
  author: VFF
  description: Install and manage Remnawave Panel via Docker Compose
  license: MIT
  min_ansible_version: "2.17"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
dependencies: []
