---
ansible_user: root
timezone: Europe/Berlin

remnawave_version: "latest"
docker_compose_dir: /opt/remnawave

# маппинг имени переменной, чтобы роль увидела нужное имя
remnawave_panel_api_token: "{{ vault_remnawave_panel_api_token }}"
